####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: lazy.ansible

###########
# Project #
###########

project:
    name: devops_project

##########
# System #
##########

system:
    # apt:
    #     packages:
    #         - jq
    git:
        config: |
            # Silence false positive dubious ownership errors
            #[safe]
            #directory = *
    ssh:
        config: |
            # Allow host autocompletion by disabling hashing in known_hosts file
            #HashKnownHosts no
            # Automatically accept host keys
            #StrictHostKeyChecking no
            # Reduce log level
            #LogLevel ERROR

            # Example
            Host *.example.com
                User foo
                ForwardAgent yes
    ansible:
        version: 2.16.2
        config: |
            [defaults]
            #force_color = True
            #retry_files_enabled = False
            [ssh_connection]
            # Improve performance
            #pipelining = True
            # Avoid issues on ssh too long socket path and/or invalid permissions
            #control_path_dir = /tmp/ansible/cp
        # dependencies:
        #     # Collection community.docker
        #     - docker==6.0.1
        #     # Collection community.hashi_vault
        #     - hvac==1.1.0
