name: devops_project

services:

    ##########
    # System #
    ##########

    system:
        hostname: devops_project
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: devops_project:20240425100046
        volumes:
            - ../..:${MANALA_DIR}
        environment:
            MANALA_DIR: ${MANALA_DIR}
            MANALA_CACHE_DIR: ${MANALA_CACHE_DIR}
        working_dir: ${MANALA_DIR}
        # Use default docker bridge network
        network_mode: bridge
