all:

  hosts:

    vm-cloud-prod-01:
      ansible_host: 152.228.212.65
      ansible_user: debian
      
    vm-cloud-stag-01:
      ansible_host: 152.228.211.237
      ansible_user: debian

  children:

    webservers:

      hosts:

        vm-cloud-prod-01: ~
        vm-cloud-stag-01: ~

    dbservers:

      hosts:

        vm-cloud-prod-01: ~
        vm-cloud-stag-01: ~

    staging:

      hosts:

        vm-cloud-stag-01: ~

    production:

      hosts:

        vm-cloud-prod-01: ~        